<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2014-08-08 22:57:12
 * @@Modify Date: 2015-04-25 22:46:01
 * @@Function:
 */
 ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $helpLabels = $this->helper('alothemes/labels');
    $helpTimer  = $this->helper('alothemes/timer'); $num = 1;
?>

<div class="mage-magictabs mc-<?php echo $this->getType();?>">
    <?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <?php 
        $config = $this->getWidgetCfg(); 
        $width  = $config['widthImages'];
        $height = $config['heightImages'];
        $actions = isset($config['action']) ? $config['action'] : array();
    ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_rowCount = isset($config['row']) ? $config['row'] : 1; //$this->getColumnCount(); ?>
    <?php $j=0; $time = isset($config['productDelay']) ? $config['productDelay'] : 0; ?>
    <?php $tag = ($_rowCount >1) ? 'div' : 'ul'; ?>
    <<?php echo $tag ?> class="flexisel-content products-grid <?php echo $this->getType();?> zoomOut play">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($_rowCount > 1 && $i++%$_rowCount==0): ?>
            <ul class="products-grid-rows">
        <?php endif ?>
            <?php $t = $j*$time; $t .='ms'; $j++; ?>

                <li style="<?php echo "-webkit-animation-delay:$t;-moz-animation-delay:$t;-o-animation-delay:$t;animation-delay:$t" ?>;" class="item item-animate">
                    <div class="per-product">
                        <div class="images-container">
						     <div class="product-hover">
								<?php //echo $helpLabels->getLabels($_product); //Product labels ?>
                                <?php echo $helpTimer->getTimer($_product, $num); $num++;//Product Timer ?>
							</div>
                            <?php if($actions): ?>
                            <div class="actions-no hover-box">
                                <div class="actions">
                                    <?php if(in_array("cart", $actions)):?>
                                        <?php if($_product->isSaleable()): ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if(in_array("wishlist", $actions)):?>
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <li class="pull-left"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><i class="fa fa-heart-o"></i><?php echo $this->__('Add to Wishlist') ?></a></li>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <?php if(in_array("compare", $actions)):?>
                                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                <li class="pull-left"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><i class="fa fa-refresh"></i><?php echo $this->__('Add to Compare') ?></a></li>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </ul>
                                     <?php if(in_array("review", $actions)):?>
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                    <?php endif ?>
                                </div>
                            </div>
                            <?php endif ?>
                        </div>
                        <div class="products-textlink clearfix">
                            <?php echo $this->getPriceHtml($_product, true) ?>
                            <div class="shop-now">
                                <a href="<?php echo $_product->getProductUrl() ?>" >
                                    <?php echo $this->__('Shop Now') ?>
                                </a>
                            </div>
                         </div>
                    
    				</div>
                </li>
            <?php if ($_rowCount > 1 && $i%$_rowCount==0 || $i==$_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
    </<?php echo $tag; ?>>
<?php endif; ?>
</div>


