<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-07-18 20:49:45
 * @@Modify Date: 2014-08-20 22:49:21
 * @@Function:
 */
?>
<?php
$helper = Mage::helper('magicsocial');
if(!$helper->getGeneralCfg('enabled')) return;
$socialCfg  = $helper->getSocialCfg();
$socials    = array( 'facebook', 'twitter', 'googleplus',
                 'linkedin', 'youtube', 'pinterest',
                 'instagram', 'flickr', 'tumblr',
                 'web',
                );
$position   = isset($socialCfg['position']) ? $socialCfg['position'] : '';
$marginTop  = isset($socialCfg['marginTop']) ? 'style="margin-top: '.$socialCfg['marginTop'].'px"' : '';
?>
<div class="social-icons <?php echo $position ?>" <?php echo $marginTop ?>>
    <?php foreach ($socials as $social): ?>
        <?php $url = $social .'_url'; $title =  $social .'_title'; ?>
        <?php if (isset($socialCfg[$url]) && $socialCfg[$url]): ?>
            <a class="socialitems" target="_blank" href="<?php echo $socialCfg[$url] ?>"
               id="<?php echo $social ?>-btn">
                <span class="social-icon">
                    <span class="social-text"><?php echo $this->__($socialCfg[$title]) ?></span>
                </span>
            </a>
        <?php endif; ?>
    <?php endforeach ?>

    <?php if (isset($socialCfg['webmail']) && $socialCfg['webmail']): ?>
        <a class="socialitems" target="_blank" href="mailto:<?php echo $socialCfg['webmail'] ?>"
           id="mail-btn">
            <span class="social-icon">
                <span
                    class="social-text"><?php echo $this->__($socialCfg['webmail_title']) ?></span>
            </span>
        </a>
    <?php endif; ?>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('.social-icons .social-icon').mouseenter(function () {
            $(this).stop();
            $(this).animate({width: '160'}, 500, '<?php  echo isset($socialCfg['effect']) ? $socialCfg['effect'] : '' ?>', function () {
            });
        });
        $('.social-icons .social-icon').mouseleave(function () {
            $(this).stop();
            $(this).animate({width: '43'}, 500, '<?php  echo isset($socialCfg['effect']) ? $socialCfg['effect'] : '' ?>', function () {
            });
        });        
    }); 
</script>
