<?php
if(!Mage::helper('blog')->isEnabled()) return;
$_hpImages = Mage::helper('blog/images');
$rows 	= $this->getRow() ? $this->getRow() : 1;
$width  = $this->getData('widthImages') ? $this->getData('widthImages') : 135;
$height = $this->getData('heightImages') ? $this->getData('heightImages') : 135;
?>

<?php if ($posts = $this->getRecent()):  $i = 1;?>
<?php $selector = $this->generateRandomString(); //md5(rand()); //rand(0,666666); ?>
<?php 
	$margin  = (int) $this->getData('marginColumn');
	$slide   = json_encode($this->setFlexiselArray());
	$options = json_encode($this->getItemsDevice());
?>
	<div class="<?php echo $selector?>">
		<div class="blogtabs block-title-tabs">
			<h3 class="item active loaded section-title title_left" data-type ="blog"><span><?php echo $this->__($this->getTitle()) ?></span>
			</h3>
		</div>
		<div class="content-blog" data-margin="<?php echo $margin ?>" data-slider='<?php echo $slide ?>' data-options='<?php echo $options; ?>'>
			<div class="mc-blog">
				<ul class="flexisel-content">
					<?php foreach ($posts as $post): ?>
						<li class="item">
						   <div class="postcontent">
							    <div class="blog-image al-style-2 image-container">
									<a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getImage() ? '<img  class="img-responsive" src="'. $_hpImages->resizeImg(basename($post->getImage()), $width, $height) .'" alt="imgBlog"/>' : ''; ?></a>
								    
								</div>
								<div class="blog_short_text clearfix">
								    <div class="blog_text">
										<?php $s = $post->getCreatedTime(); $date = strtotime($s); ?>
										<div class="post-date">
										   <span><?php echo date("d M Y", $date) ?></span>
										   <!--<?php //echo $this->__('By'). '<span class="title">' .$post->getUser(). '</span>' ;?>
										   <span class="comments"><?php //echo $post->getCommentCount().' '. $this->__('comments') ?></span>-->
										</div>
										 <a href="<?php echo $post->getAddress(); ?>" ><?php echo '<span class="title">'.$post->getTitle().'</span>' ?>
										 </a>
										<!--<div class="shortcontent-text">
											<p class="short-text"><?php //echo $this->getContentBlogSidebar(strip_tags($post->getShortContent()),120);?>...
											</p>
										</div>-->
										<a class="read-more-blog" href="<?php echo $post->getAddress(); ?>"><?php echo $this->__('Read more') ;?><i class="fa fa-angle-double-right"></i></a>
									</div>
								</div>
							</div>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>			
		</div>
	</div>
<?php endif ?>
<script type="text/javascript">
jQuery(document).ready(function () {
	jQuery(".<?php echo $selector?>").magicproduct({
		tabs  : '.blogtabs',
		product  : '.content-blog',
	});
});
</script>
