<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="blog-toolbar blog-toolbar-top">
   <?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
</div>
<?php 
$_hpImages = Mage::helper('blog/images');
$width  = 870;
$height = 870;
?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        
        <div class="blog-poss">
        	<div class="blog-head post-date clearfix">
				<div class="postDetails">
	            	<div class="number"><span><?php echo $post->getCreatedTime(); ?></span></div>
	            </div>
            </div>
			<div class="postTitle">
				<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
			</div>
			<div class="by post-date clearfix">
				<div class="postDetails">
					<?php if ($this->getCommentsEnabled()): ?>
						<?php //echo $post->getCommentCount(); ?> <!--<a href="<?php //echo $post->getAddress(); ?>#commentBox" > <?php //echo Mage::helper('blog')->__('Comments'); ?></a>-->
					<?php endif; ?>
					<?php $postCats = $post->getCats(); ?>
					<?php if (!empty($postCats)): ?>
						<?php //echo Mage::helper('blog')->__('Posted in'); ?>
						<?php foreach ($postCats as $data): ?>
							<!--<a href="<?php //echo $data['url']; ?>"><?php //echo $data['title']; ?></a>-->
						<?php endforeach; ?>
					<?php else: ?>
						<?php //echo Mage::helper('blog')->__('Posted'); ?>
					<?php endif; ?><span class="posted"><?php echo $this->__("Post By:"); ?></span> <span class="user"><?php echo $post->getUser(); ?></span>
				</div>
				<!--<span class="comments"><?php //echo $post->getCommentCount().' '. $this->__('comments') ?></span>-->
			</div>
			<a class="blog-img" href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getImage() ? '<img  class="img-responsive" src="'. $_hpImages->resizeImg(basename($post->getImage()), $width, $height) .'">' : ''; ?></a>
			<?php echo $this->getTagsHtml($post) ?>
			<?php echo $this->getBookmarkHtml($post) ?>
			<div class="postContent"><?php echo $post->getPostContent(); ?></div>
		</div>
    </div>
<?php endforeach; ?>
<div class="blog-toolbar blog-toolbar-bottom clearfix">
<?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
</div>
